<script lang="ts">
  import type { Exhibition } from "$lib/types";

  export let item: Exhibition;

  const images: string[] = [
    "/images/interference_2023/03.jpg",
    "/images/interference_2023/02.jpg",
  ];
</script>

<main>
  <p>
    <span class="el-date">{item.date}</span>
    <span class="el-loc">{item.location}</span>
  </p>
  <h1 class="el-title focus">{item.title}</h1>
  <br />
  <p class="short-desc">{item.shortDesc}</p>
  <div class="image-text-container">
    <div class="long-desc">
      <p>
        интерference is a first time collaboration between Anastasia Zhylinskaya
        and Jun Suzuki that brings together their combined interests in
        generative and installation art. Resulting from a 2 weeks residency in
        Tusheti, Georgia (about 10 km from the Russian frontier), the artists
        explore their interpretation of borders and what evade them : natural
        elements and electromagnetic waves.
      </p>
      <p>
        Using contact microphones loosely attached to metal rods subject to
        outdoors elements, and an omnidirectional geophone that captures the
        faintest vibrations on the floor, wind, rain and footsteps become
        triggers of enveloping soundscapes. The sounds generated by the natural
        elements outside are amplified and processed by modular synthesis and
        submerge the room into an endless sombre drone punctuated by crashing
        roars of metal rods.
      </p>
      <p>
        Simultaneously, each footstep randomly triggers a new short-term
        frequency from an SDR (Software Defined Radio) playing broadcasts from
        all over the world, thus switching from music, news and talks to machine
        bleeps and static noise. In times of political conflicts and compromised
        boundaries, the artists question the inevitability of history, and how
        sound and unscripted noise cut across these borders to transmit an
        alternative sense of togetherness.
      </p>
    </div>

    <img src={item.coverImg} alt={item.title} class="cover-img" />
  </div>

  <div class="gallery">
    {#each images as image}
      <img src={image} alt={item.title} class="gallery-image" />
    {/each}
  </div>
</main>

<style>
  .long-desc {
    background-color: var(--dark-mode-bg);
    padding: 2rem;
  }
</style>
